const dotenv = require('dotenv');
dotenv.config();
const { 
  NODE_ENV,FRONTEND_URL,STRIPE_SERVICE,USUARIO_SERVICE,PORT,SECRET_JWT_KEY,WISHLIST_SERVICE,PRODUCTO_SERVICE, ENVIOS_SERVICE
}= process.env;

module.exports = {
  USUARIO_SERVICE,
  PORT,
  NODE_ENV,
  FRONTEND_URL,
  SECRET_JWT_KEY,WISHLIST_SERVICE,
  PRODUCTO_SERVICE,
  ENVIOS_SERVICE,
  STRIPE_SERVICE
};