const dotenv = require('dotenv');
dotenv.config();
const { 
  NODE_ENV,FRONTEND_URL,USUARIO_SERVICE,APP_PORT,SECRET_JWT_KEY,WISHLIST_SERVICE,PRODUCTO_SERVICE
}= process.env;

module.exports = {
  USUARIO_SERVICE,
  APP_PORT,
  NODE_ENV,
  FRONTEND_URL,
  SECRET_JWT_KEY,WISHLIST_SERVICE,
  PRODUCTO_SERVICE
};